"""
transform_duckdb.py
-------------------
This module handles all DuckDB-related transformations for GTFS-RT + static GTFS.
It:
  - Creates views on static GTFS CSV files
  - Loads realtime snapshots into persistent tables
  - Builds analytics marts (aggregated tables)
  - Exports marts to Parquet for Power BI
"""

import duckdb
from pathlib import Path
from datetime import datetime

# Paths (inside Docker these should be /opt/airflow/...)
DATA_DIR = Path("/opt/airflow/data")
WAREHOUSE = Path("/opt/airflow/warehouse/lignesazur.duckdb")
EXPORTS = Path("/opt/airflow/exports")


def _con():
    """
    Ensure warehouse folder exists and return a DuckDB connection.
    """
    WAREHOUSE.parent.mkdir(parents=True, exist_ok=True)
    return duckdb.connect(str(WAREHOUSE))


def init_db():
    """
    Initialize DuckDB with some settings (e.g., multi-threading).
    """
    con = _con()
    con.sql("PRAGMA threads=4;")
    con.close()


def load_static_gtfs():
    """
    Create views over the static GTFS CSVs.
    Views = lightweight pointers, no data copy.
    """
    con = _con()
    con.sql(
        f"""
    CREATE VIEW IF NOT EXISTS stg_routes AS
    SELECT * FROM read_csv('{DATA_DIR/'routes.txt'}', AUTO_DETECT=TRUE);
    
    CREATE VIEW IF NOT EXISTS stg_trips AS
    SELECT * FROM read_csv('{DATA_DIR/'trips.txt'}', AUTO_DETECT=TRUE);
    
    CREATE VIEW IF NOT EXISTS stg_stops AS
    SELECT * FROM read_csv('{DATA_DIR/'stops.txt'}', AUTO_DETECT=TRUE);
    
    CREATE VIEW IF NOT EXISTS stg_stop_times AS
    SELECT * FROM read_csv('{DATA_DIR/'stop_times.txt'}', AUTO_DETECT=TRUE);
    """
    )
    con.close()


def load_rt_snapshots():
    """
    Load realtime CSVs (generated by extract_rt.py) into persistent DuckDB tables.
    Each run appends new rows (historical record).
    """
    con = _con()

    # Create tables if missing
    con.sql(
        """
    CREATE TABLE IF NOT EXISTS rt_trips (
        trip_id VARCHAR, route_id VARCHAR, stop_id VARCHAR,
        arrival_delay BIGINT, departure_delay BIGINT,
        event_ts TIMESTAMP
    );
    """
    )
    con.sql(
        """
    CREATE TABLE IF NOT EXISTS rt_vehicle (
        vehicle_id VARCHAR, trip_id VARCHAR, route_id VARCHAR,
        latitude DOUBLE, longitude DOUBLE, bearing DOUBLE, speed DOUBLE,
        ts TIMESTAMP
    );
    """
    )

    # Only load if file exists & not empty
    rt_trips_file = DATA_DIR / "rt_trips.csv"
    if rt_trips_file.exists() and rt_trips_file.stat().st_size > 0:
        con.sql(
            f"""
        INSERT INTO rt_trips
        SELECT
            trip_id::VARCHAR,
            route_id::VARCHAR,
            stop_id::VARCHAR,
            NULLIF(arrival_delay, '')::BIGINT,
            NULLIF(departure_delay, '')::BIGINT,
            CAST(event_ts AS TIMESTAMP)
        FROM read_csv_auto('{rt_trips_file}');
        """
        )

    rt_vehicle_file = DATA_DIR / "rt_vehicle.csv"
    if rt_vehicle_file.exists() and rt_vehicle_file.stat().st_size > 0:
        con.sql(
            f"""
        INSERT INTO rt_vehicle
        SELECT
            vehicle_id::VARCHAR,
            trip_id::VARCHAR,
            route_id::VARCHAR,
            latitude::DOUBLE,
            longitude::DOUBLE,
            bearing::DOUBLE,
            speed::DOUBLE,
            CAST(timestamp AS TIMESTAMP)
        FROM read_csv_auto('{rt_vehicle_file}');
        """
        )

    con.close()


def build_core_marts():
    """
    Build star schema & marts for analytics.
    Fact = stop events
    Dimensions = routes, stops
    Aggregates = by time, by route, by stop
    """
    con = _con()

    # Fact table: stop events with delays
    con.sql(
        """
    CREATE TABLE IF NOT EXISTS fact_stop_events AS
    SELECT
        r.route_id,
        t.trip_id,
        e.stop_id,
        COALESCE(e.arrival_delay, e.departure_delay) AS delay_sec,
        COALESCE(e.arrival_delay, e.departure_delay) / 60.0 AS delay_min,
        e.event_ts,
        date_trunc('day', e.event_ts) AS event_date,
        extract(hour from e.event_ts) AS event_hour,
        strftime(e.event_ts, '%w')::INT AS dow
    FROM rt_trips e
    JOIN stg_trips t ON t.trip_id = e.trip_id
    JOIN stg_routes r ON r.route_id = e.route_id
    WHERE e.stop_id IS NOT NULL
      AND COALESCE(e.arrival_delay, e.departure_delay) IS NOT NULL
      AND ABS(COALESCE(e.arrival_delay, e.departure_delay)) < 36000; -- cap 10h
    """
    )

    # Dimensions
    con.sql("CREATE OR REPLACE TABLE dim_routes AS SELECT * FROM stg_routes;")
    con.sql("CREATE OR REPLACE TABLE dim_stops AS SELECT * FROM stg_stops;")

    # Aggregates
    con.sql(
        """
    CREATE OR REPLACE TABLE mart_delay_by_time AS
    SELECT event_date, event_hour,
           AVG(delay_min) AS avg_delay_min,
           COUNT(*) AS n_obs
    FROM fact_stop_events
    GROUP BY event_date, event_hour;
    """
    )
    con.sql(
        """
    CREATE OR REPLACE TABLE mart_route_delay AS
    SELECT route_id, AVG(delay_min) AS avg_delay_min, COUNT(*) AS n_obs
    FROM fact_stop_events
    GROUP BY route_id;
    """
    )
    con.sql(
        """
    CREATE OR REPLACE TABLE mart_stop_delay AS
    SELECT stop_id, AVG(delay_min) AS avg_delay_min, COUNT(*) AS n_obs
    FROM fact_stop_events
    GROUP BY stop_id;
    """
    )

    con.close()


def export_for_powerbi():
    """
    Export marts into Parquet files for Power BI.
    Timestamp in filename = snapshot history.
    """
    con = _con()
    EXPORTS.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M")

    con.sql(
        f"COPY mart_delay_by_time TO '{EXPORTS/f'mart_delay_by_time_{ts}.parquet'}' (FORMAT 'parquet');"
    )
    con.sql(
        f"COPY mart_route_delay TO '{EXPORTS/f'mart_route_delay_{ts}.parquet'}' (FORMAT 'parquet');"
    )
    con.sql(
        f"COPY mart_stop_delay TO '{EXPORTS/f'mart_stop_delay_{ts}.parquet'}' (FORMAT 'parquet');"
    )

    # Latest vehicle snapshot (optional for mapping)
    con.sql(
        f"""
    COPY (
      SELECT * FROM rt_vehicle
      WHERE ts > NOW() - INTERVAL 30 MINUTE
    ) TO '{EXPORTS/f'vehicles_latest_{ts}.parquet'}' (FORMAT 'parquet');
    """
    )
    con.close()


def cleanup_old_data(days: int = 7):
    """
    Optional: delete RT records older than X days (keeps DB small).
    """
    con = _con()
    con.sql(f"DELETE FROM rt_trips WHERE event_ts < NOW() - INTERVAL {days} DAY;")
    con.sql(f"DELETE FROM rt_vehicle WHERE ts < NOW() - INTERVAL {days} DAY;")
    con.close()
